# IAM Resources - Region: ap-south-1
# Generated by AWS Scanner

resource "aws_iam_user" "scaner_user" {
  name = "scaner-user"
}

resource "aws_iam_user" "ses_smtp_user_20251114_144538" {
  name = "ses-smtp-user.20251114-144538"
}

resource "aws_iam_user" "SESSendEmailOnly" {
  name = "SESSendEmailOnly"
}

resource "aws_iam_user" "WebApsterTechnologies" {
  name = "WebApsterTechnologies"
}

