# LAMBDA Resources - Region: ap-south-1
# Generated by AWS Scanner

resource "aws_lambda_function" "terraformer_test_api_dev_scan" {
  function_name = "terraformer-test-api-dev-scan"
  role          = "arn:aws:iam::529928147507:role/terraformer-test-api-dev-ap-south-1-lambdaRole"
  handler       = "src/handlers/scan.handler"
  runtime       = "nodejs18.x"
  timeout       = 30
  memory_size   = 1024

  environment {
    variables = {
      "NODE_ENV" = "dev"
    }
  }

  # Note: The 'filename' or 's3_*' arguments are required but cannot be scanned
  # You'll need to manually specify the deployment package
  filename = "lambda_function.zip"  # Update this
}

