# S3 Resources - Region: ap-south-1
# Generated by AWS Scanner

resource "aws_s3_bucket" "imu_labs_api_service_prod_serverlessdeploymentbuck_gwem4nuqgjfq" {
  bucket = "imu-labs-api-service-prod-serverlessdeploymentbuck-gwem4nuqgjfq"
}

resource "aws_s3_bucket" "infrasync" {
  bucket = "infrasync"
}

resource "aws_s3_bucket" "serverless_framework_deployments_us_east_1_1e0b675d_952d" {
  bucket = "serverless-framework-deployments-us-east-1-1e0b675d-952d"
}

resource "aws_s3_bucket" "terraformer_test_api_dev_serverlessdeploymentbucke_pwxd2irfmgmi" {
  bucket = "terraformer-test-api-dev-serverlessdeploymentbucke-pwxd2irfmgmi"
}

resource "aws_s3_bucket" "test_bucket_linxus_infrasync" {
  bucket = "test-bucket-linxus-infrasync"
}

resource "aws_s3_bucket" "testing_infrasync" {
  bucket = "testing-infrasync"
}

